endpoint = "http://0.0.0.0:8000"
electrum_server = "" # Empty string for Mock Electrum server
testing_mode = "true" # Use testing wallet
network = "testnet"
daemon_address = "/tmp/rustd.sock"
[tor]
enable = false
proxy = "socks5h://127.0.0.1:9050"
