endpoint = "https://fakeapi.mercurywallet.io"
electrum_server = "electrum.blockstream.info:60001" # Empty string for Mock Electrum server
testing_mode = "false" # Use testing wallet
network = "testnet"
daemon_address = "/tmp/rustd.sock"
[tor]
enable = false
proxy = "socks5h://127.0.0.1:9050"
