electrum_server = "127.0.0.1:60401"
network = "testnet"
required_confirmation = 0
testing_mode = false
lockheight_init = 1000
lh_decrement = 10

# Fees
fee_address = "tb1qzvv6yfeg0navfkrxpqc0fjdsu9ey4qgqqsarq4,tb1qzvv6yfeg0navfkrxpqc0fjdsu9ey4qgqqsarq4"
fee_deposit = 0
fee_withdraw = 300

# Swap parameters
punishment_duration = "180" # 3 minute
utxo_timeout = "60"
batch_lifetime = "180" # 3 minute

#Mainstay config
mainstay_config = ""

#Watch config
watch_only = false
bitcoind = ""

#Rate limiter for certain API calls
rate_limit = 9999999999999