electrum_server = "127.0.0.1:60401"
lockbox = ""
network = "testnet"
block_time = 2
testing_mode = true
# log_file = "log/output.log" # Comment out for stdout
lockheight_init = 1000
lh_decrement = 10

# Fees
fee_address = "tb1qzvv6yfeg0navfkrxpqc0fjdsu9ey4qgqqsarq4"
fee_deposit = 0
fee_withdraw = 300

# Swap parameters
punishment_duration = "3600" # 1 hour
batch_lifetime = "3600" # 1 hour

#Mainstay config
mainstay_config = ""

#Watch config
watch_only = false
bitcoind = ""
